

development:
  adapter: postgresql
  encoding: utf8
  database: korrp_dev
  username: postgres
  password: admin56mus
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: utf8
  database: korrp_test
  username: postgres
  password: admin56mus
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: utf8
  database: korrp
  username: postgres
  password: admin56mus
  host: localhost
  port: 5432

#poltax:
#  adapter: oracle_enhanced
#  database: //10.xxx.xxx.xxx:1521/PLTX
#  username: pass
#  password: pass  